version: "3.2"

services:
  registry:
    build: 
      context: ./registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
    #   - registry-data:/var/lib/registry
    restart: unless-stopped

# volumes:
#   registry-data:
